apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default: # this section defines default limits
      cpu: "1"
      memory: 512Mi
    defaultRequest: # this section defines default requests
      cpu: "0.5"
      memory: 256Mi
    max: # max and min define the limit range
      cpu: "2"
      memory: 512Mi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container

# LimitRange is a policy that constraints the resource allocation
# It can enforce minimum and maximum compute resources usage per Pod or Container or even PVC in a namespace
# The difference between LimitRange and ResourceQuota is so;
# ResourceQuota is the total available resources for a particular namespace, while LimitRange is used to assign limits for containers running inside the namespace.