apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
spec:
  hard:
    pods: "2"
    services.nodeports: "1"
    services.loadbalancers: "0"
    persistentvolumeclaims: "2"

# In kubernetes, we can restrict the number of API objects, including pods, persistent volume claims and services, that can be created in a namespace