apiVersion: v1
kind: Pod
metadata:
  name: memory-limit
spec:
  containers:
  - name: memory-limit
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"] #250M

# The args section in the configuration file provides arguments for the container when it starts
# The --vm-bytes, 150M arguments tell the Container to attempt to allocate 150 MiB of memory
# The container would be using more than requested memory unless exceeding the limitation
# If the container were to allocate 250 MiB of memory, it would be killed exceeding the allocated memory