apiVersion: v1
kind: Pod
metadata:
  name: clarus-db
  labels:
    tier: db
spec:
  containers:
  - name: clarus-db
    image: clarusway/clarusdb
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clarusshop
  labels:
    app: clarusshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: clarusshop
  template:
    metadata:
      labels:
        app: clarusshop
    spec:
      containers:
      - name: clarusshop
        image: clarusway/clarusshop
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - db
            topologyKey: "kubernetes.io/hostname"

# Notice that the clarusshop pods are assigned to the same node with clarus-db pod