apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: mynginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /test
      name: emptydir-test
  volumes:
  - name: emptydir-test
    emptyDir:
