apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - {{ .Values.volumes.accessMode }}
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}