apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cronjob-container
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c", "date; echo Hello World"]
          restartPolicy: Never

# The cronjob creates a job that will run every minute