apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 6
  parallelism: 2 
  template:
    spec:
      containers:
      - name: hello-job-container
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo hello;sleep 10;echo world"]
      restartPolicy: Never

# The job creates 6 pods, with a  maximum of two pods running concurrently