apiVersion: v1
kind: Service   
metadata:
  name: clarusshop-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    version: v1
    # version: v2 # When deployment and testing succeed, you may switch to the green environment

# Blue-green deployment splits your application environment into equally sourced sections; blue and green
# You serve the current application on one half of your environment blue