apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    env: dev
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "wget -O /data/index.html http://info.cern.ch"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    env: dev
  ports:
    - nodePort: 30036
      port: 80
      targetPort: 80