apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  containers:
  - name: httpd-container
    image: httpd:alpine
    volumeMounts:
    - name: shared-data
      mountPath: /usr/local/apache2/htdocs
  - name: alpine-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: [ "-c", "echo hello world > /pod-data/index.html && sleep 3600" ]
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: